#!/bin/bash

# Script to automatically update the email-signature data file
# Run this script whenever you add new images to the email-signature folder

echo "Scanning for PNG and JPG files in email-signature folder..."

DATA_FILE="_data/email-signature.yml"
EMAIL_SIG_DIR="email-signature"

# Create backup of existing data file
if [ -f "$DATA_FILE" ]; then
    cp "$DATA_FILE" "${DATA_FILE}.backup"
    echo "Created backup of existing data file"
fi

# Start writing the new data file
cat > "$DATA_FILE" << 'EOF'
# Email signature images
# Auto-generated by update-email-signature-data.sh
# Update descriptions manually as needed

images:
EOF

# Find all PNG and JPG files and add them to the data file
find "$EMAIL_SIG_DIR" -type f \( -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg" \) | sort | while read -r file; do
    filename=$(basename "$file")
    name=$(echo "$filename" | sed 's/\.[^.]*$//' | sed 's/-/ /g' | sed 's/\b\w/\U&/g')
    extension="${filename##*.}"
    
    cat >> "$DATA_FILE" << EOF
  - filename: "$filename"
    name: "$name"
    description: "Auto-detected image file"
    type: "${extension,,}"
  
EOF
done

echo "Updated $DATA_FILE with $(grep -c 'filename:' "$DATA_FILE") image files"
echo "You may want to manually edit the descriptions in $DATA_FILE"
